# Generated by Django 5.2 on 2025-04-04 16:26

import django.db.models.deletion
import documentacion.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Normas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("norma", models.CharField(max_length=50)),
                ("punto_norma", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Documentos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_de_documento",
                    models.CharField(
                        choices=[
                            ("PROCEDIMIENTO", "Procedimiento"),
                            ("MANUAL", "Manual"),
                            ("INSTRUCTIVO", "Instructivo"),
                            ("FORMATO", "Formato"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        max_length=50, validators=[documentacion.models.validar_codigo]
                    ),
                ),
                ("nombre_documento", models.CharField(max_length=100)),
                (
                    "estatus",
                    models.CharField(
                        choices=[
                            ("ACTIVO", "Activo"),
                            ("OBSOLETO", "Obsoleto"),
                            ("ELABORACION", "En Elaboración"),
                            ("ACTUALIZACION", "En Actualización"),
                            ("REVISION", "En Revisión"),
                            ("APROBACION", "En Aprobación"),
                            ("PUBLICADO", "Publicado"),
                        ],
                        max_length=20,
                    ),
                ),
                ("version", models.IntegerField()),
                (
                    "frecuencia_evaluacion",
                    models.IntegerField(
                        choices=[
                            (1, "1 mes"),
                            (2, "2 meses"),
                            (3, "3 meses"),
                            (4, "4 meses"),
                            (5, "5 meses"),
                            (6, "6 meses"),
                            (12, "12 meses"),
                        ]
                    ),
                ),
                ("vigencia_documento", models.DateField()),
                ("localidad", models.CharField(max_length=50)),
                ("creador", models.CharField(max_length=50)),
                ("carpeta", models.CharField(max_length=100)),
                (
                    "documento_original",
                    models.FileField(upload_to=documentacion.models.ruta_documentos),
                ),
                ("usuarios_distribucion", models.JSONField(blank=True, default=list)),
                ("grupos_distribucion", models.JSONField(blank=True, default=list)),
                ("puestos_distribucion", models.JSONField(blank=True, default=list)),
                ("procesos_distribucion", models.JSONField(blank=True, default=list)),
                ("documentos_relacionados", models.JSONField(blank=True, default=list)),
                ("revisor", models.JSONField(blank=True, default=list)),
                ("aprobador", models.JSONField(blank=True, default=list)),
                ("publicador", models.JSONField(blank=True, default=list)),
                ("fecha_publicacion", models.DateField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateField(auto_now=True, null=True)),
                ("fecha_obsoleto", models.DateField(blank=True, null=True)),
                ("comentarios_alta", models.TextField(blank=True)),
                ("motivo_cambio", models.TextField(blank=True)),
                ("motivo_baja", models.TextField(blank=True)),
                (
                    "norma",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="documentos_norma",
                        to="documentacion.normas",
                    ),
                ),
                (
                    "punto_norma",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="documentos_punto_norma",
                        to="documentacion.normas",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RegistroEvento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("accion", models.CharField(max_length=100)),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                (
                    "documento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="eventos",
                        to="documentacion.documentos",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
