"""
Django settings for adeweb project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-$4anv-()8kv-7oe@$t-av3n1rjknhpqf0o)8y5d-c%8v)jg^nu"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost', '127.0.0.1']

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django_plotly_dash",
    'dpd_static_support',
    'channels',
    "usuarios",
    "dashboard",
    ]   

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    'django_plotly_dash.middleware.BaseMiddleware',
    'django_plotly_dash.middleware.ExternalRedirectionMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    ]

STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    'django_plotly_dash.finders.DashAssetFinder',
    'django_plotly_dash.finders.DashComponentFinder',
    'django_plotly_dash.finders.DashAppDirectoryFinder',
    ]

PLOTLY_DASH = {
    "inject_dash_apps_scripts": True,  # Cambiado a False
    "inject_plotly": True,

    "serve_locally": False,
    # "insert_demo_migrations": False,
    # "inject_stylesheet": True,
    "external_stylesheets": [
        '/static/css/styles.css',  # Tu hoja de estilos personalizada
    ],
    "external_scripts": [
        "https://unpkg.com/react@16.14.0/umd/react.production.min.js",
        "https://unpkg.com/react-dom@16.14.0/umd/react-dom.production.min.js",
        "https://unpkg.com/prop-types@15.8.1/prop-types.min.js",
        "https://cdn.plot.ly/plotly-latest.min.js",
        "https://unpkg.com/dash-core-components@2.0.0/dash_core_components/dash_core_components.min.js",
        "https://unpkg.com/dash-html-components@2.0.0/dash_html_components/dash_html_components.min.js",
        "https://unpkg.com/dash-renderer@1.9.1/dash_renderer/dash_renderer.min.js",
    ],

}

ROOT_URLCONF = "adeweb.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                ],
            },
        },
    ]

WSGI_APPLICATION = "adeweb.wsgi.application"

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
        },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
        },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
        },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
        },
    ]

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "es-mx"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "/static/"

# STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
#TATIC_ROOT = BASE_DIR / 'staticfiles'

#STATICFILES_DIRS = [
#    BASE_DIR, 'static',
#    ]

STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Authentication settings
LOGIN_URL = 'usuarios:login'  # Use the name of your login URL pattern
LOGIN_REDIRECT_URL = 'usuarios:home'  # Where to redirect after login
LOGOUT_REDIRECT_URL = 'usuario:login'  # Where to redirect after logout

AUTH_USER_MODEL = 'usuarios.CustomUser'

EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
# DEFAULT_FROM_EMAIL = 'daniel.santoyo@dilusa.mx'

# Add these settings for django_plotly_dash
X_FRAME_OPTIONS = 'SAMEORIGIN'

PLOTLY_COMPONENTS = [
    'dash_core_components',
    'dash_html_components',
    'dash_renderer',
    'dpd_components',
    'dash_table',
    ]
