# Generated by Django 5.2 on 2025-06-26 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CertificadoCalidad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField(auto_now_add=True)),
                ("cliente", models.CharField(max_length=50)),
                ("producto", models.CharField(max_length=50)),
                ("lote", models.IntegerField()),
                ("clave", models.IntegerField()),
                ("cantidad", models.FloatField()),
                ("fecha_elaboracion", models.DateField()),
                ("fecha_caducidad", models.DateField()),
                ("mesofilicos", models.FloatField(blank=True)),
                ("coliformes", models.FloatField(blank=True)),
                ("e_coli", models.FloatField(blank=True)),
                ("hongos", models.FloatField(blank=True)),
                ("levaduras", models.FloatField(blank=True)),
                ("salmonella_spp", models.CharField(blank=True, max_length=50)),
                ("listeria_mono", models.CharField(blank=True, max_length=50)),
                ("staphylococcus", models.CharField(blank=True, max_length=50)),
                ("acidez", models.FloatField(blank=True)),
                ("peroxidos", models.FloatField(blank=True)),
                ("humedad", models.FloatField(blank=True)),
                ("materia_extraña", models.CharField(max_length=50)),
                ("olor", models.CharField(max_length=50)),
                ("sabor", models.CharField(max_length=50)),
                ("color", models.CharField(max_length=50)),
                ("textura", models.CharField(max_length=50)),
                ("aspecto", models.CharField(max_length=50)),
                ("observaciones", models.TextField(blank=True)),
                (
                    "documento_word",
                    models.FileField(blank=True, upload_to="certificados/word/"),
                ),
                (
                    "documento_pdf",
                    models.FileField(blank=True, upload_to="certificados/pdf/"),
                ),
            ],
        ),
    ]
